// Templates de flux pré-configurés pour ETICA
// Ces templates permettent aux utilisateurs de démarrer rapidement avec des patterns communs

import { NodeFunctionType, NodeEntityType } from '@/components/canvas/custom-node'

export interface FlowTemplateNode {
  id: string
  type: NodeFunctionType
  entityType?: NodeEntityType
  label: string
  description: string
  dataTypes: string[]
  position: { x: number; y: number }
  inputCount?: number
  outputCount?: number
}

export interface FlowTemplateEdge {
  id: string
  source: string
  sourceHandle?: string
  target: string
  targetHandle?: string
  label?: string
  dataTypes: string[]
  domains: string[]
}

export interface FlowTemplate {
  id: string
  name: string
  description: string
  category: string
  icon: string
  vigilanceLevel: number
  typicalTensions: string[]
  nodes: FlowTemplateNode[]
  edges: FlowTemplateEdge[]
}

export const FLOW_TEMPLATES: FlowTemplate[] = [
  {
    id: 'credit-scoring',
    name: 'Scoring de crédit',
    description: 'Système d\'évaluation automatisée de solvabilité pour l\'octroi de crédits',
    category: 'Finance',
    icon: '💳',
    vigilanceLevel: 4,
    typicalTensions: ['EFFICIENCY_VS_TRANSPARENCY', 'PERFORMANCE_VS_EQUITY', 'AUTOMATION_VS_RECOURSE', 'CONTROL_VS_INNOVATION', 'BALANCE_VS_EFFICIENCY'],
    nodes: [
      {
        id: 'client',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Demandeur de crédit',
        description: 'Personne physique demandant un crédit',
        dataTypes: ['NAME', 'DOB', 'SSN', 'INCOME', 'EMPLOYMENT'],
        position: { x: 50, y: 200 },
        outputCount: 2,
      },
      {
        id: 'data-sources',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'Sources de données',
        description: 'Bases de données bancaires et bureaux de crédit',
        dataTypes: ['TRANSACTIONS', 'CREDIT_SCORE', 'BANK_ACCOUNT'],
        position: { x: 50, y: 350 },
        outputCount: 1,
      },
      {
        id: 'aggregator',
        type: 'TREATMENT',
        entityType: 'INFRA',
        label: 'Agrégation données',
        description: 'Consolidation des données du demandeur',
        dataTypes: ['INCOME', 'TRANSACTIONS', 'CREDIT_SCORE'],
        position: { x: 280, y: 275 },
        inputCount: 2,
        outputCount: 1,
      },
      {
        id: 'ml-model',
        type: 'DECISION',
        entityType: 'AI',
        label: 'Modèle de scoring ML',
        description: 'Algorithme de prédiction de risque de défaut',
        dataTypes: ['SCORE', 'PREDICTION', 'CATEGORY'],
        position: { x: 500, y: 275 },
        inputCount: 1,
        outputCount: 2,
      },
      {
        id: 'advisor',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Conseiller bancaire',
        description: 'Agent humain validant la décision',
        dataTypes: ['DECISION'],
        position: { x: 720, y: 200 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'notification',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Notification client',
        description: 'Communication de la décision au demandeur',
        dataTypes: ['DECISION'],
        position: { x: 720, y: 350 },
        inputCount: 1,
      },
      {
        id: 'storage',
        type: 'STORAGE',
        entityType: 'INFRA',
        label: 'Archivage décision',
        description: 'Conservation des données de décision',
        dataTypes: ['SCORE', 'DECISION', 'INCOME'],
        position: { x: 940, y: 275 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-client-aggregator',
        source: 'client',
        sourceHandle: 'output-0',
        target: 'aggregator',
        targetHandle: 'input-0',
        label: 'Données personnelles',
        dataTypes: ['NAME', 'DOB', 'SSN', 'INCOME', 'EMPLOYMENT'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-sources-aggregator',
        source: 'data-sources',
        sourceHandle: 'output-0',
        target: 'aggregator',
        targetHandle: 'input-1',
        label: 'Historique financier',
        dataTypes: ['TRANSACTIONS', 'CREDIT_SCORE', 'BANK_ACCOUNT'],
        domains: ['PRIVACY', 'SECURITY'],
      },
      {
        id: 'e-aggregator-model',
        source: 'aggregator',
        sourceHandle: 'output-0',
        target: 'ml-model',
        targetHandle: 'input-0',
        label: 'Données consolidées',
        dataTypes: ['INCOME', 'TRANSACTIONS', 'CREDIT_SCORE'],
        domains: ['TRANSPARENCY'],
      },
      {
        id: 'e-model-advisor',
        source: 'ml-model',
        sourceHandle: 'output-0',
        target: 'advisor',
        targetHandle: 'input-0',
        label: 'Score et recommandation',
        dataTypes: ['SCORE', 'PREDICTION'],
        domains: ['TRANSPARENCY', 'EQUITY'],
      },
      {
        id: 'e-model-notification',
        source: 'ml-model',
        sourceHandle: 'output-1',
        target: 'notification',
        targetHandle: 'input-0',
        label: 'Résultat automatique',
        dataTypes: ['DECISION'],
        domains: ['RECOURSE', 'AUTONOMY'],
      },
      {
        id: 'e-advisor-storage',
        source: 'advisor',
        sourceHandle: 'output-0',
        target: 'storage',
        targetHandle: 'input-0',
        label: 'Décision finale',
        dataTypes: ['DECISION', 'SCORE'],
        domains: ['RESPONSIBILITY'],
      },
    ],
  },
  {
    id: 'recruitment-screening',
    name: 'Tri de candidatures',
    description: 'Système de présélection automatisée des CV pour le recrutement',
    category: 'RH',
    icon: '👥',
    vigilanceLevel: 4,
    typicalTensions: ['PERFORMANCE_VS_EQUITY', 'AUTOMATION_VS_RECOURSE', 'PREDICTION_VS_FREEWILL', 'RESPONSIBILITY_VS_AGILITY', 'BALANCE_VS_EFFICIENCY'],
    nodes: [
      {
        id: 'candidate',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Candidat',
        description: 'Personne postulant à une offre d\'emploi',
        dataTypes: ['NAME', 'EMAIL', 'CV', 'EDUCATION', 'SKILLS'],
        position: { x: 50, y: 250 },
        outputCount: 1,
      },
      {
        id: 'ats',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'ATS',
        description: 'Applicant Tracking System - réception des candidatures',
        dataTypes: ['CV', 'EMAIL', 'NAME'],
        position: { x: 250, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'parser',
        type: 'TREATMENT',
        entityType: 'AI',
        label: 'Extraction CV',
        description: 'Parsing et extraction des informations du CV',
        dataTypes: ['EDUCATION', 'SKILLS', 'EMPLOYMENT'],
        position: { x: 450, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'scoring',
        type: 'DECISION',
        entityType: 'AI',
        label: 'Scoring candidature',
        description: 'Évaluation et classement des candidatures',
        dataTypes: ['SCORE', 'CATEGORY'],
        position: { x: 650, y: 250 },
        inputCount: 1,
        outputCount: 2,
      },
      {
        id: 'recruiter',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Recruteur',
        description: 'Agent RH validant la présélection',
        dataTypes: ['DECISION'],
        position: { x: 850, y: 150 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'rejection',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Rejet automatique',
        description: 'Email de refus automatique',
        dataTypes: ['EMAIL'],
        position: { x: 850, y: 350 },
        inputCount: 1,
      },
      {
        id: 'interview',
        type: 'ACTION',
        entityType: 'ORG',
        label: 'Convocation entretien',
        description: 'Invitation à un entretien',
        dataTypes: ['EMAIL', 'NAME'],
        position: { x: 1050, y: 150 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-candidate-ats',
        source: 'candidate',
        target: 'ats',
        label: 'Candidature',
        dataTypes: ['NAME', 'EMAIL', 'CV'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-ats-parser',
        source: 'ats',
        target: 'parser',
        label: 'CV brut',
        dataTypes: ['CV'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-parser-scoring',
        source: 'parser',
        target: 'scoring',
        label: 'Données structurées',
        dataTypes: ['EDUCATION', 'SKILLS', 'EMPLOYMENT'],
        domains: ['TRANSPARENCY'],
      },
      {
        id: 'e-scoring-recruiter',
        source: 'scoring',
        sourceHandle: 'output-0',
        target: 'recruiter',
        label: 'Top candidats',
        dataTypes: ['SCORE', 'CATEGORY'],
        domains: ['EQUITY', 'TRANSPARENCY'],
      },
      {
        id: 'e-scoring-rejection',
        source: 'scoring',
        sourceHandle: 'output-1',
        target: 'rejection',
        label: 'Candidats écartés',
        dataTypes: ['EMAIL'],
        domains: ['RECOURSE', 'AUTONOMY'],
      },
      {
        id: 'e-recruiter-interview',
        source: 'recruiter',
        target: 'interview',
        label: 'Validation humaine',
        dataTypes: ['DECISION'],
        domains: ['RESPONSIBILITY'],
      },
    ],
  },
  {
    id: 'recommendation-engine',
    name: 'Moteur de recommandation',
    description: 'Système de recommandation personnalisée de contenus ou produits',
    category: 'Commerce',
    icon: '🎯',
    vigilanceLevel: 3,
    typicalTensions: ['PERSONALIZATION_VS_AUTONOMY', 'PRECISION_VS_MINIMIZATION', 'ACCESSIBILITY_VS_CONTROL', 'SOVEREIGNTY_VS_PERFORMANCE', 'LOYALTY_VS_PROFIT'],
    nodes: [
      {
        id: 'user',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Utilisateur',
        description: 'Visiteur du site ou application',
        dataTypes: ['BROWSING', 'PURCHASES', 'PREFERENCES'],
        position: { x: 50, y: 250 },
        outputCount: 2,
      },
      {
        id: 'tracking',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'Tracking comportemental',
        description: 'Collecte des interactions utilisateur',
        dataTypes: ['BROWSING', 'INTERACTIONS', 'GPS'],
        position: { x: 280, y: 150 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'profile-db',
        type: 'STORAGE',
        entityType: 'INFRA',
        label: 'Base de profils',
        description: 'Historique et préférences utilisateurs',
        dataTypes: ['PURCHASES', 'PREFERENCES', 'CATEGORY'],
        position: { x: 280, y: 350 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'aggregation',
        type: 'TREATMENT',
        entityType: 'INFRA',
        label: 'Agrégation profil',
        description: 'Construction du profil unifié',
        dataTypes: ['BROWSING', 'PURCHASES', 'PREFERENCES'],
        position: { x: 500, y: 250 },
        inputCount: 2,
        outputCount: 1,
      },
      {
        id: 'reco-engine',
        type: 'DECISION',
        entityType: 'AI',
        label: 'Moteur de reco IA',
        description: 'Algorithme de recommandation ML',
        dataTypes: ['PREDICTION', 'SCORE'],
        position: { x: 720, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'display',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Affichage personnalisé',
        description: 'Présentation des recommandations',
        dataTypes: ['PREDICTION'],
        position: { x: 940, y: 250 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-user-tracking',
        source: 'user',
        sourceHandle: 'output-0',
        target: 'tracking',
        label: 'Navigation',
        dataTypes: ['BROWSING', 'INTERACTIONS'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-user-profile',
        source: 'user',
        sourceHandle: 'output-1',
        target: 'profile-db',
        label: 'Achats/préfs',
        dataTypes: ['PURCHASES', 'PREFERENCES'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-tracking-agg',
        source: 'tracking',
        target: 'aggregation',
        targetHandle: 'input-0',
        label: 'Comportement récent',
        dataTypes: ['BROWSING', 'INTERACTIONS'],
        domains: ['PRIVACY', 'AUTONOMY'],
      },
      {
        id: 'e-profile-agg',
        source: 'profile-db',
        target: 'aggregation',
        targetHandle: 'input-1',
        label: 'Historique',
        dataTypes: ['PURCHASES', 'PREFERENCES'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-agg-reco',
        source: 'aggregation',
        target: 'reco-engine',
        label: 'Profil complet',
        dataTypes: ['BROWSING', 'PURCHASES', 'PREFERENCES'],
        domains: ['TRANSPARENCY', 'AUTONOMY'],
      },
      {
        id: 'e-reco-display',
        source: 'reco-engine',
        target: 'display',
        label: 'Recommandations',
        dataTypes: ['PREDICTION', 'SCORE'],
        domains: ['AUTONOMY', 'TRANSPARENCY'],
      },
    ],
  },
  {
    id: 'fraud-detection',
    name: 'Détection de fraude',
    description: 'Système de détection automatique des transactions frauduleuses',
    category: 'Finance',
    icon: '🔒',
    vigilanceLevel: 3,
    typicalTensions: ['SECURITY_VS_PRIVACY', 'SPEED_VS_REFLECTION', 'AUTOMATION_VS_RECOURSE', 'CONTROL_VS_INNOVATION'],
    nodes: [
      {
        id: 'customer',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Client',
        description: 'Titulaire du compte effectuant une transaction',
        dataTypes: ['NAME', 'BANK_ACCOUNT', 'GPS'],
        position: { x: 50, y: 250 },
        outputCount: 1,
      },
      {
        id: 'transaction',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'Transaction',
        description: 'Données de la transaction en cours',
        dataTypes: ['TRANSACTIONS', 'GPS', 'IP_ADDRESS'],
        position: { x: 250, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'enrichment',
        type: 'TREATMENT',
        entityType: 'INFRA',
        label: 'Enrichissement',
        description: 'Ajout du contexte historique',
        dataTypes: ['TRANSACTIONS', 'TRAVEL_HISTORY', 'PURCHASES'],
        position: { x: 450, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'fraud-model',
        type: 'DECISION',
        entityType: 'AI',
        label: 'Détection fraude IA',
        description: 'Modèle ML de scoring de risque',
        dataTypes: ['SCORE', 'PREDICTION'],
        position: { x: 650, y: 250 },
        inputCount: 1,
        outputCount: 3,
      },
      {
        id: 'approve',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Approbation',
        description: 'Transaction autorisée',
        dataTypes: ['DECISION'],
        position: { x: 880, y: 100 },
        inputCount: 1,
      },
      {
        id: 'analyst',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Analyste fraude',
        description: 'Revue manuelle des cas suspects',
        dataTypes: ['TRANSACTIONS', 'SCORE'],
        position: { x: 880, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'block',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Blocage',
        description: 'Transaction bloquée automatiquement',
        dataTypes: ['DECISION'],
        position: { x: 880, y: 400 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-customer-tx',
        source: 'customer',
        target: 'transaction',
        label: 'Initiation paiement',
        dataTypes: ['BANK_ACCOUNT', 'GPS'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-tx-enrich',
        source: 'transaction',
        target: 'enrichment',
        label: 'Données transaction',
        dataTypes: ['TRANSACTIONS', 'GPS', 'IP_ADDRESS'],
        domains: ['PRIVACY', 'SECURITY'],
      },
      {
        id: 'e-enrich-fraud',
        source: 'enrichment',
        target: 'fraud-model',
        label: 'Données enrichies',
        dataTypes: ['TRANSACTIONS', 'TRAVEL_HISTORY'],
        domains: ['TRANSPARENCY'],
      },
      {
        id: 'e-fraud-approve',
        source: 'fraud-model',
        sourceHandle: 'output-0',
        target: 'approve',
        label: 'Risque faible',
        dataTypes: ['DECISION'],
        domains: ['SECURITY'],
      },
      {
        id: 'e-fraud-analyst',
        source: 'fraud-model',
        sourceHandle: 'output-1',
        target: 'analyst',
        label: 'Cas suspect',
        dataTypes: ['SCORE', 'TRANSACTIONS'],
        domains: ['RECOURSE', 'TRANSPARENCY'],
      },
      {
        id: 'e-fraud-block',
        source: 'fraud-model',
        sourceHandle: 'output-2',
        target: 'block',
        label: 'Risque élevé',
        dataTypes: ['DECISION'],
        domains: ['SECURITY', 'RECOURSE'],
      },
    ],
  },
  {
    id: 'chatbot-support',
    name: 'Chatbot service client',
    description: 'Assistant conversationnel automatisé pour le support client',
    category: 'Service',
    icon: '💬',
    vigilanceLevel: 2,
    typicalTensions: ['AUTOMATION_VS_RECOURSE', 'EFFICIENCY_VS_TRANSPARENCY', 'WELLBEING_VS_AUTONOMY', 'SOVEREIGNTY_VS_PERFORMANCE', 'PERFORMANCE_VS_SUSTAINABILITY'],
    nodes: [
      {
        id: 'customer',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Client',
        description: 'Utilisateur posant une question',
        dataTypes: ['NAME', 'EMAIL'],
        position: { x: 50, y: 250 },
        outputCount: 1,
      },
      {
        id: 'chatbot',
        type: 'DECISION',
        entityType: 'AI',
        label: 'Chatbot IA',
        description: 'Agent conversationnel génératif',
        dataTypes: ['INTERACTIONS', 'PREFERENCES'],
        position: { x: 300, y: 250 },
        inputCount: 1,
        outputCount: 2,
      },
      {
        id: 'response',
        type: 'ACTION',
        entityType: 'AI',
        label: 'Réponse automatique',
        description: 'Réponse générée par l\'IA',
        dataTypes: ['INTERACTIONS'],
        position: { x: 550, y: 150 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'escalation',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Escalade',
        description: 'Transfert vers un agent humain',
        dataTypes: ['INTERACTIONS'],
        position: { x: 550, y: 350 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'agent',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Agent support',
        description: 'Conseiller humain pour les cas complexes',
        dataTypes: ['INTERACTIONS', 'DECISION'],
        position: { x: 800, y: 350 },
        inputCount: 1,
      },
      {
        id: 'feedback',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'Retour client',
        description: 'Évaluation de la satisfaction',
        dataTypes: ['SCORE', 'INTERACTIONS'],
        position: { x: 800, y: 150 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-customer-chatbot',
        source: 'customer',
        target: 'chatbot',
        label: 'Question',
        dataTypes: ['INTERACTIONS'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-chatbot-response',
        source: 'chatbot',
        sourceHandle: 'output-0',
        target: 'response',
        label: 'Réponse IA',
        dataTypes: ['INTERACTIONS'],
        domains: ['TRANSPARENCY', 'AUTONOMY'],
      },
      {
        id: 'e-chatbot-escalation',
        source: 'chatbot',
        sourceHandle: 'output-1',
        target: 'escalation',
        label: 'Cas complexe',
        dataTypes: ['INTERACTIONS'],
        domains: ['RECOURSE'],
      },
      {
        id: 'e-escalation-agent',
        source: 'escalation',
        target: 'agent',
        label: 'Transfert',
        dataTypes: ['INTERACTIONS'],
        domains: ['RECOURSE', 'RESPONSIBILITY'],
      },
      {
        id: 'e-response-feedback',
        source: 'response',
        target: 'feedback',
        label: 'Demande de feedback',
        dataTypes: ['SCORE'],
        domains: ['AUTONOMY'],
      },
    ],
  },
  {
    id: 'medical-diagnosis',
    name: 'Aide au diagnostic médical',
    description: 'Système d\'aide au diagnostic assisté par IA pour les médecins',
    category: 'Santé',
    icon: '🏥',
    vigilanceLevel: 5,
    typicalTensions: ['EFFICIENCY_VS_TRANSPARENCY', 'INNOVATION_VS_PRECAUTION', 'AUTOMATION_VS_RECOURSE', 'CONTROL_VS_INNOVATION', 'RESPONSIBILITY_VS_AGILITY'],
    nodes: [
      {
        id: 'patient',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Patient',
        description: 'Personne consultant pour un diagnostic',
        dataTypes: ['NAME', 'DOB', 'MEDICAL_RECORD', 'ALLERGIES'],
        position: { x: 50, y: 250 },
        outputCount: 1,
      },
      {
        id: 'ehr',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'Dossier médical',
        description: 'Electronic Health Record du patient',
        dataTypes: ['MEDICAL_RECORD', 'TREATMENTS', 'ALLERGIES'],
        position: { x: 250, y: 150 },
        outputCount: 1,
      },
      {
        id: 'symptoms',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'Symptômes actuels',
        description: 'Données cliniques de la consultation',
        dataTypes: ['MEDICAL_RECORD'],
        position: { x: 250, y: 350 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'analysis',
        type: 'TREATMENT',
        entityType: 'AI',
        label: 'Analyse IA',
        description: 'Traitement et analyse des données médicales',
        dataTypes: ['MEDICAL_RECORD', 'PREDICTION'],
        position: { x: 480, y: 250 },
        inputCount: 2,
        outputCount: 1,
      },
      {
        id: 'diagnosis',
        type: 'DECISION',
        entityType: 'AI',
        label: 'Suggestion diagnostic',
        description: 'Proposition de diagnostics probables',
        dataTypes: ['PREDICTION', 'SCORE'],
        position: { x: 700, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'doctor',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Médecin',
        description: 'Professionnel validant le diagnostic',
        dataTypes: ['DECISION', 'MEDICAL_RECORD'],
        position: { x: 920, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'treatment',
        type: 'ACTION',
        entityType: 'ORG',
        label: 'Prescription',
        description: 'Traitement prescrit au patient',
        dataTypes: ['TREATMENTS'],
        position: { x: 1120, y: 250 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-patient-symptoms',
        source: 'patient',
        target: 'symptoms',
        label: 'Consultation',
        dataTypes: ['MEDICAL_RECORD'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-ehr-analysis',
        source: 'ehr',
        target: 'analysis',
        targetHandle: 'input-0',
        label: 'Historique médical',
        dataTypes: ['MEDICAL_RECORD', 'TREATMENTS', 'ALLERGIES'],
        domains: ['PRIVACY', 'SECURITY'],
      },
      {
        id: 'e-symptoms-analysis',
        source: 'symptoms',
        target: 'analysis',
        targetHandle: 'input-1',
        label: 'Symptômes',
        dataTypes: ['MEDICAL_RECORD'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-analysis-diagnosis',
        source: 'analysis',
        target: 'diagnosis',
        label: 'Données analysées',
        dataTypes: ['MEDICAL_RECORD', 'PREDICTION'],
        domains: ['TRANSPARENCY'],
      },
      {
        id: 'e-diagnosis-doctor',
        source: 'diagnosis',
        target: 'doctor',
        label: 'Suggestions IA',
        dataTypes: ['PREDICTION', 'SCORE'],
        domains: ['TRANSPARENCY', 'RESPONSIBILITY'],
      },
      {
        id: 'e-doctor-treatment',
        source: 'doctor',
        target: 'treatment',
        label: 'Décision médicale',
        dataTypes: ['TREATMENTS'],
        domains: ['RESPONSIBILITY', 'RECOURSE'],
      },
    ],
  },
  {
    id: 'llm-assistant',
    name: 'Assistant IA générative',
    description: 'Application utilisant un LLM externe pour générer du contenu ou répondre aux questions',
    category: 'IA Générative',
    icon: '🤖',
    vigilanceLevel: 4,
    typicalTensions: ['SOVEREIGNTY_VS_PERFORMANCE', 'PERFORMANCE_VS_SUSTAINABILITY', 'CONTROL_VS_INNOVATION', 'LOYALTY_VS_PROFIT', 'BALANCE_VS_EFFICIENCY'],
    nodes: [
      {
        id: 'user',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Utilisateur',
        description: 'Personne interagissant avec l\'assistant',
        dataTypes: ['INTERACTIONS', 'PREFERENCES'],
        position: { x: 50, y: 250 },
        outputCount: 1,
      },
      {
        id: 'app',
        type: 'TREATMENT',
        entityType: 'INFRA',
        label: 'Application',
        description: 'Interface et logique métier',
        dataTypes: ['INTERACTIONS', 'CONTEXT'],
        position: { x: 250, y: 250 },
        inputCount: 1,
        outputCount: 2,
      },
      {
        id: 'llm-api',
        type: 'DECISION',
        entityType: 'AI',
        label: 'API LLM externe',
        description: 'Service d\'IA générative tiers (OpenAI, Anthropic, etc.)',
        dataTypes: ['INTERACTIONS', 'PREDICTION'],
        position: { x: 500, y: 150 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'local-db',
        type: 'STORAGE',
        entityType: 'INFRA',
        label: 'Base de contexte',
        description: 'Données métier et historique (RAG)',
        dataTypes: ['CONTEXT', 'INTERACTIONS'],
        position: { x: 500, y: 350 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'moderator',
        type: 'TREATMENT',
        entityType: 'AI',
        label: 'Modération',
        description: 'Filtrage et vérification des sorties',
        dataTypes: ['INTERACTIONS'],
        position: { x: 720, y: 250 },
        inputCount: 2,
        outputCount: 1,
      },
      {
        id: 'response',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Réponse',
        description: 'Affichage de la réponse à l\'utilisateur',
        dataTypes: ['INTERACTIONS'],
        position: { x: 940, y: 250 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-user-app',
        source: 'user',
        target: 'app',
        label: 'Question/Requête',
        dataTypes: ['INTERACTIONS'],
        domains: ['PRIVACY'],
      },
      {
        id: 'e-app-llm',
        source: 'app',
        sourceHandle: 'output-0',
        target: 'llm-api',
        label: 'Prompt enrichi',
        dataTypes: ['INTERACTIONS', 'CONTEXT'],
        domains: ['SOVEREIGNTY', 'PRIVACY'],
      },
      {
        id: 'e-app-db',
        source: 'app',
        sourceHandle: 'output-1',
        target: 'local-db',
        label: 'Requête contexte',
        dataTypes: ['CONTEXT'],
        domains: ['MASTERY'],
      },
      {
        id: 'e-llm-mod',
        source: 'llm-api',
        target: 'moderator',
        targetHandle: 'input-0',
        label: 'Réponse brute',
        dataTypes: ['PREDICTION'],
        domains: ['TRANSPARENCY', 'MASTERY'],
      },
      {
        id: 'e-db-mod',
        source: 'local-db',
        target: 'moderator',
        targetHandle: 'input-1',
        label: 'Contexte vérifié',
        dataTypes: ['CONTEXT'],
        domains: ['TRANSPARENCY'],
      },
      {
        id: 'e-mod-response',
        source: 'moderator',
        target: 'response',
        label: 'Réponse filtrée',
        dataTypes: ['INTERACTIONS'],
        domains: ['SECURITY', 'RESPONSIBILITY'],
      },
    ],
  },
  {
    id: 'predictive-maintenance',
    name: 'Maintenance prédictive',
    description: 'Système IoT pour anticiper les pannes et optimiser la maintenance industrielle',
    category: 'Industrie',
    icon: '🏭',
    vigilanceLevel: 3,
    typicalTensions: ['PERFORMANCE_VS_SUSTAINABILITY', 'CONTROL_VS_INNOVATION', 'RESPONSIBILITY_VS_AGILITY', 'SUSTAINABILITY_VS_ACCESSIBILITY'],
    nodes: [
      {
        id: 'sensors',
        type: 'SOURCE',
        entityType: 'INFRA',
        label: 'Capteurs IoT',
        description: 'Capteurs sur les équipements industriels',
        dataTypes: ['SENSOR_DATA', 'TELEMETRY'],
        position: { x: 50, y: 250 },
        outputCount: 1,
      },
      {
        id: 'edge',
        type: 'TREATMENT',
        entityType: 'INFRA',
        label: 'Edge computing',
        description: 'Prétraitement local des données',
        dataTypes: ['SENSOR_DATA', 'AGGREGATED'],
        position: { x: 250, y: 250 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'cloud-ml',
        type: 'DECISION',
        entityType: 'AI',
        label: 'Modèle prédictif cloud',
        description: 'Analyse ML pour prédiction de pannes',
        dataTypes: ['PREDICTION', 'SCORE'],
        position: { x: 480, y: 250 },
        inputCount: 1,
        outputCount: 2,
      },
      {
        id: 'alert',
        type: 'ACTION',
        entityType: 'INFRA',
        label: 'Alerte maintenance',
        description: 'Notification aux équipes terrain',
        dataTypes: ['PREDICTION'],
        position: { x: 720, y: 150 },
        inputCount: 1,
      },
      {
        id: 'technician',
        type: 'STAKEHOLDER',
        entityType: 'HUMAN',
        label: 'Technicien',
        description: 'Personnel de maintenance',
        dataTypes: ['DECISION'],
        position: { x: 720, y: 350 },
        inputCount: 1,
        outputCount: 1,
      },
      {
        id: 'intervention',
        type: 'ACTION',
        entityType: 'ORG',
        label: 'Intervention',
        description: 'Opération de maintenance planifiée',
        dataTypes: ['DECISION'],
        position: { x: 940, y: 350 },
        inputCount: 1,
      },
    ],
    edges: [
      {
        id: 'e-sensors-edge',
        source: 'sensors',
        target: 'edge',
        label: 'Données brutes',
        dataTypes: ['SENSOR_DATA', 'TELEMETRY'],
        domains: ['MASTERY'],
      },
      {
        id: 'e-edge-cloud',
        source: 'edge',
        target: 'cloud-ml',
        label: 'Données agrégées',
        dataTypes: ['AGGREGATED'],
        domains: ['SOVEREIGNTY', 'SUSTAINABILITY'],
      },
      {
        id: 'e-cloud-alert',
        source: 'cloud-ml',
        sourceHandle: 'output-0',
        target: 'alert',
        label: 'Prédiction urgente',
        dataTypes: ['PREDICTION'],
        domains: ['SECURITY'],
      },
      {
        id: 'e-cloud-tech',
        source: 'cloud-ml',
        sourceHandle: 'output-1',
        target: 'technician',
        label: 'Rapport prédictif',
        dataTypes: ['PREDICTION', 'SCORE'],
        domains: ['TRANSPARENCY', 'RESPONSIBILITY'],
      },
      {
        id: 'e-tech-intervention',
        source: 'technician',
        target: 'intervention',
        label: 'Décision humaine',
        dataTypes: ['DECISION'],
        domains: ['RESPONSIBILITY', 'SOCIETAL_BALANCE'],
      },
    ],
  },
]

export function getTemplateById(id: string): FlowTemplate | undefined {
  return FLOW_TEMPLATES.find(t => t.id === id)
}

export function getTemplatesByCategory(category: string): FlowTemplate[] {
  return FLOW_TEMPLATES.filter(t => t.category === category)
}

export const TEMPLATE_CATEGORIES = Array.from(new Set(FLOW_TEMPLATES.map(t => t.category)))
